import { GameListGame } from '@/app/types/GameListTypes'

export const dummyGameListGames: GameListGame[] =
  [
    {
      hostUsername: 'cosmosis',
      hostSocketId: '1234',
      rating: 1000,
      time: 30,
      isInProgress: false,
    },
    {
      hostUsername: 'denizen_don',
      hostSocketId: '1234',
      rating: 1300,
      time: 15,
      isInProgress: false,
    },
    {
      hostUsername: 'romantic_rain',
      hostSocketId: '1234',
      rating: 800,
      time: 30,
      isInProgress: false,
    },
    {
      hostUsername: 'billiam',
      hostSocketId: '1234',
      rating: 900,
      time: 20,
      isInProgress: false,
    },
    {
      hostUsername: 'rondosis',
      hostSocketId: '1234',
      rating: 1100,
      time: 25,
      isInProgress: false,
    },
    {
      hostUsername: 'quazzyqua',
      hostSocketId: '1234',
      rating: 1200,
      time: 35,
      isInProgress: false,
    },
    {
      hostUsername: 'timbers',
      hostSocketId: '1234',
      rating: 950,
      time: 40,
      isInProgress: false,
    },
    {
      hostUsername: 'tropical_trey',
      hostSocketId: '1234',
      rating: 1050,
      time: 10,
      isInProgress: false,
    },
    {
      hostUsername: 'twizzler',
      hostSocketId: '1234',
      rating: 1400,
      time: 50,
      isInProgress: false,
    },
    {
      hostUsername: 'fonkrow',
      hostSocketId: '1234',
      rating: 850,
      time: 20,
      isInProgress: false,
    },
    {
      hostUsername: 'finchma',
      hostSocketId: '1234',
      rating: 950,
      time: 15,
      isInProgress: false,
    },
    {
      hostUsername: 'scrazzle',
      hostSocketId: '1234',
      rating: 1200,
      time: 25,
      isInProgress: false,
    },
    {
      hostUsername: 'mbongogon',
      hostSocketId: '1234',
      rating: 800,
      time: 35,
      isInProgress: false,
    },
  ]
