import { GameListGame } from '@/app/types/GameListTypes'

export const dummyGameListGames: GameListGame[] =
  [
    {
      hostUsername: 'willing_chocolate_locust',
      rating: 1000,
      time: 30,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 30,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'excited_pineapple_frog',
      rating: 1200,
      time: 45,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 45,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'happy_mango_butterfly',
      rating: 800,
      time: 60,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 60,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'playful_banana_dolphin',
      rating: 1500,
      time: 30,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 30,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'curious_strawberry_turtle',
      rating: 1100,
      time: 45,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 45,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'energetic_watermelon_squirrel',
      rating: 900,
      time: 60,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 60,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'clever_orange_monkey',
      rating: 1300,
      time: 30,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 30,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'joyful_grapefruit_elephant',
      rating: 1000,
      time: 45,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 45,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'friendly_pineapple_bird',
      rating: 1400,
      time: 60,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 60,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'creative_kiwi_fox',
      rating: 950,
      time: 30,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 30,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    },
    {
      hostUsername: 'brave_mango_butterfly',
      rating: 1150,
      time: 45,
      isInProgress: false,
      hasGameStarted: false,
      currentWord: '',
      isHostsTurn: true,
      isBeingRewarded: false,
      isBeingPenalized: false,
      hostTime: 45,
      timerInterval: null,
      lastTimeUpdateTimestamp: 0
    }
  ]
